name: RustDesk Test

on:
  workflow_dispatch:

jobs:
  rustdesk:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run RustDesk PowerShell script
      shell: pwsh
      run: |
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
        ./scripts/rustdesk.ps1

    - name: Upload credentials file
      uses: actions/upload-artifact@v4
      with:
        name: rustdesk-output
        path: RustDesk_Credentials.txt
